### PR TITLE
Make the app itself using Vue to fix accessibility

### LINKED ISSUE #898: [BITV] Accessibility issues
## Bug fixes
* [x] #1019
* [x] #1020
* [ ] Clicking on a file should ideally open the image or file in place: right now a redirection to files takes place. File will be opened "in place".

Following suggestions were moved to main "Lazy loading" https://github.com/nextcloud/server/issues/33844 issue: 
 - navigation via months/time could be useful
 - filtering/search would be useful

### LINKED ISSUE #903: [BITV] Lazy loading is not accessible
"Lazy loading not accessible as you can not move very far to the past quickly. Pagination would be much better here"

Applies to:
- [ ] the main activity list
- [ ] might apply to activities within the files app sidebar

Potential idea: using role=feed but beware of shortcomings.

### LINKED ISSUE #1360: [BITV]: Sidebar is broken
### Steps to reproduce
1. Open any page in activity app
2. Open sidebar

image

### Expected behaviour
Sidebar is not broken. Please replace current sidebar with a sidebar from NcVue.

### LINKED ISSUE #1362: Compatibility with `@nextcloud/vue` 8
For the next release we need compatibility with `@nextcloud/vue` 8 as this is the version that will be used with Nextcloud 28.

Ref: https://github.com/nextcloud-libraries/nextcloud-vue/issues/4223

*This is just a reminder issue, I assigned myself and will work on this.*

### PR DESCRIPTION
**Pull request by susnux**
* Resolves #1360
* Resolves #1362
* Possible in follow up (PR already too big): #903 and #898

Move the main app to Vue instead of handlebars + j.Query to align with our work on accessibility in the `@nextcloud/vue` project.

### Screenshot of the new vue app
image

### CODE REVIEW

File: lib/Controller/SettingsController.php [hunk 1]
```diff
@@ -183,13 +183,13 @@ public function admin(
 	/**
 	 * @NoAdminRequired
 	 *
-	 * @param string $enable	'true' if the feed is enabled
+	 * @param bool $enable true if the feed is enabled
 	 * @return DataResponse
 	 */
 	public function feed($enable) {
```
Comment (artonge) [inline lib/Controller/SettingsController.php:189]:
```suggestion
	public function feed(bool $enable) {
```

File: src/routes.ts [hunk 2]
```diff
@@ -32,6 +16,28 @@
...
+import type { RouteConfig } from 'vue-router'
+import ActivityAppFeed from './views/ActivityAppFeed.vue'
+import ActivityAppNavigation from './views/ActivityAppNavigation.vue'
+
+export const routes = [
+	{
+		path: '/',
+		name: 'root',
+		redirect: { path: '/all' },
+	},
```
Comment (ShGKme) [inline src/routes.ts:32]: Do we need to change the URL of the root page? Maybe use 'all' as a fallback value in one route?

File: src/components/Activity.vue [hunk 3]
```diff
@@ -25,21 +25,37 @@
...
+				v-for="preview, index in activity.previews"
+				:key="preview.fileId ?? `preview-${index}`"
+				class="activity-entry__preview"
+				:href="preview.link">
+				<img class="activity-entry__preview-image"
+					:class="{
+						'activity-entry__preview-mimetype': preview.isMimeTypeIcon,
+					}"
+					:src="preview.source"
+					:alt="preview.link ? t('activity', 'Open {filename}', preview) : ''">
```
Comment (ShGKme) [inline src/components/Activity.vue:47]: Shouldn't the param be passed as `t('activity', 'Open {filename}', { filename: preview })`?

File: src/settings-personal.js [hunk 4]
```diff
@@ -24,15 +24,11 @@ import Vuex from 'vuex'
...
 import DailySummary from './views/DailySummary.vue'
 import { translate as t, translatePlural as n } from '@nextcloud/l10n'
-import { generateFilePath } from '@nextcloud/router'
 import store from './settings-store.js'
 
 Vue.prototype.t = t
 Vue.prototype.n = n
 
-// eslint-disable-next-line no-undef, camelcase
-__webpack_public_path__ = generateFilePath(appName, '', 'js/')
```
Comment (artonge) [inline src/settings-personal.js:34]: This is not necessary anymore as we use vite, right ?

Comment (susnux) [reply src/settings-personal.js:34]: Right this now done with `renderBuiltUrl` in the viteconfig

File: src/components/Activity.vue (hunk 3 above)
Comment (susnux) [reply src/components/Activity.vue:47]: no but I can make it more explicit like this:
`t('activity', 'Open {filename}', { filename: preview.filename })`

File: src/routes.ts (hunk 2 above)
Comment (susnux) [reply src/routes.ts:32]: This makes it easier as then the sidebar item for `all activities` is automatically active on the root page.
Otherwise the route does not match the navigation entry which needs more changes to work.

**Review by artonge — APPROVED** [review]

**Comment by susnux** [comment]
I give up on this and used the compile bot, absolutely no idea what is going on with the CI when I build locally.
