### PR TITLE
[stable27] Fix unit tests for PHP 8.2

### LINKED ISSUE #1179: Unit tests don't execute against php 8.2
Should be added for master and stable27

### PR DESCRIPTION
**Pull request by susnux**
* Resolves #1179

### CODE REVIEW

File: tests/Mock/Request.php [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+declare(strict_types=1);
+namespace OCA\Activity\Tests\Mock;
+
+use OCP\IRequest;
+
+// we need dynamic properties support for the ::server property
+#[\AllowDynamicProperties]
+class Request extends IRequest {
+
+}
```
Comment (miaulalala) [inline tests/Mock/Request.php:11]: Missing a newline here?

**Review by miaulalala — DISMISSED** [review]
